### ISSUE TITLE
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\username\\AppData\\Local\\Temp\\tmp3v6qi352'

### ISSUE THREAD

**Issue by raghadalhelal** [reverseame/sigcheck#3]
I tried to execute sigvalidator.py without success.

This is my code:
```
if __name__ == '__main__':

    sigv = sigvalidator.SigValidator()
```

Here is the error message that I got

> Exception ignored in: <function SigValidator.__del__ at 0x03637100>
> Traceback (most recent call last):
>   File "C:\Users\ragehead\Yeager\venv\lib\site-packages\sigvalidator.py", line 62, in __del__
>   File "C:\Users\ragehead\Yeager\venv\lib\site-packages\sigvalidator.py", line 96, in clean_workin_dir
>   File "C:\Users\ragehead\Yeager\venv\lib\site-packages\sigvalidator.py", line 101, in delete_file
> PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\username\\AppData\\Local\\Temp\\tmp3v6qi352'

Thank you for your support

**Comment by ricardojrdez** [comment]
Hi Raghad, 
I completely forgot about this issue, my apologies. I can't recreate the problem. Can you give more details?

Maybe there is some AV analyzing the temporary file created by our tool and therefore it cannot be deleted?

**Comment by ricardojrdez** [comment]
Thanks for the report, and sorry for the long delay.

The cause is that the temporary files are removed from `__del__`, and on Windows another process (typically an antivirus scanning the freshly created file) can briefly hold a handle to it, so `os.remove` fails with WinError 32. Because this runs during garbage collection or interpreter shutdown, it showed up as the "Exception ignored in ..." traceback you saw.

I have addressed this in #9: `delete_file` now retries a few times and, if the file still cannot be removed, gives up silently instead of raising, and `__del__` no longer propagates errors. The file lives in the system temporary directory and is reclaimed by the OS.

I could not reproduce the WinError 32 directly, since it depends on a Windows host with another process holding the handle, so the change is validated against a simulated lock rather than the real antivirus interaction. If you can still reproduce it after the fix, please let me know.

**Comment by ricardojrdez** [comment]
For now, I close the issue. If you see that the problem persists, feel free to reopen or send a new issue. Thanks
